spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.42.92.57:3306/shared_bike?useSSL=false&useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: ZRSz2580
    tomcat:
      time-between-eviction-runs-millis: 600000
      min-evictable-idle-time-millis: 1800000

  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  data:
    redis:
      host: 101.42.92.57
      port: 6379
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
      password: ZRSz2580

mybatis:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.entity