server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://101.42.92.57:3306/shared_bike?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ZRSz2580

mybatis:
  mapper-locations: classpath:mapping/*.xml