server:
  port: 8085
spring:
  application:
    name: fence-service  # 要注册的服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos服务地址
  datasource:
    url: jdbc:mysql://101.42.92.57:3306/shared_bike?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ZRSz2580
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8
  web:
    resources:
      static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.train.campussharedbikeserverfence.entity

logging:
  level:
    com:
      example:
        mapper: debug

pattern:
  dateformat: yyyy-MM-dd HH:mm:ss